[project]
name = "episteval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.60.0",
    "google-genai>=1.28.0",
    "inspect-ai>=0.3.118",
    "openai>=1.98.0",
    "python-dotenv>=1.1.1",
]
